export const dataList = [
    {
      id: 1,
      nom: 'MUG',
      categorie: 'equipements',
      prix: 109,
      image: '/images/article_4.PNG',
    },
    {
      id: 2,
      nom: 'T SHIRT BATMOBILE',
      categorie: 'vêtements',
      prix: 25,
      image: '/images/article_5.PNG',
    },
    {
      id: 3,
      nom: 'HORLOGE',
      categorie: 'goodies',
      prix: 8,
      image: '/images/article_6.PNG',
    },
    {
      id: 4,
      nom: `SWEAT "WHY SO SERIOUS"`,
      categorie: 'vêtements',
      prix: 132,
      image: '/images/article_7.PNG',
    },
    {
      id: 5,
      nom: 'HORLOGE',
      categorie: 'equipements',
      prix: 198,
      image: '/images/article_8.PNG',
    },
    {
      id: 6,
      nom: 'PORTE CLE',
      categorie: 'goodies',
      prix: 25,
      image: '/images/article_10.PNG',
    },
    {
      id: 7,
      nom: 'MUD VOYAGE',
      categorie: 'equipements',
      prix: 45,
      image: '/images/article_1.PNG',
    },
    {
      id: 8,
      nom: 'POSTER BATMAN (2022)',
      categorie: 'goodies',
      prix: 10,
      image: '/images/article_2.PNG',
    },
    {
      id: 9,
      nom: 'MUG',
      categorie: 'equipements',
      prix: 15,
      image: '/images/article_3.PNG',
    },
  ];